@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMjUwZDIyYTkzODVmYzQ4NDJhYTU2YWJhZjUzZmU5NDcxNmVjNTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRyYWNrZXItMzI3MTciLCJhdWQiOiJlY28tdHJhY2tlci0zMjcxNyIsImF1dGhfdGltZSI6MTczODc5ODA0MSwidXNlcl9pZCI6IjhpaDRaYnVCdkpYWjBKS1FQcG5ZQ29HOHdlSTMiLCJzdWIiOiI4aWg0WmJ1QnZKWFowSktRUHBuWUNvRzh3ZUkzIiwiaWF0IjoxNzM4Nzk4MDQxLCJleHAiOjE3Mzg4MDE2NDEsImVtYWlsIjoiZWRhcnRlYWdhQHB1Y2UuZWR1LmVjIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImVkYXJ0ZWFnYUBwdWNlLmVkdS5lYyJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.rCUIBoYC7wbzmjyhRWP9ItzFJ0YHDXYqApsaHEyZLNZIU8YoP1elFnmgXpRy0NP_jFnaCsYl8wM5bo-aTY19kSowP_T-_Xiba5wHZaYKzGIHi9qHwmiLEcgpG08qtqxuTsaBcBRIHnfyipKj9piE6pY063xx8zDUo0Q23xEIpXnZ5Yh52QNND1iW4K-qkZ3RsuREnofgogxQ93FA1PWsvxut5e2JEHTu0sdGN0ARjrSLX1bDjIFh0TKsWarMvQXfU3GV_OJr-mDVtMqmJTcaHEm5vLQ1fW7G6vTDKqqdvCMQGfasTXFf4lgR0Ln71YDopXl_zGeo5AlJZLjr0rjtzA


### Create a new appliance
POST http://localhost:3000/appliances
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Refrigerator",
  "type": "hours_per_day",
  "kwh": 2.184
}

### Get all appliances
GET http://localhost:3000/appliances
Authorization: Bearer {{token}}

### Get an appliance by ID
GET http://localhost:3000/appliances/1
Authorization: Bearer {{token}}

### Update an appliance
PUT http://localhost:3000/appliances/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Refrigerator",
  "type": "hours_per_day",
  "kwh": 2.5
}

### Delete an appliance
DELETE http://localhost:3000/appliances/1
Authorization: Bearer {{token}}