@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMjUwZDIyYTkzODVmYzQ4NDJhYTU2YWJhZjUzZmU5NDcxNmVjNTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRyYWNrZXItMzI3MTciLCJhdWQiOiJlY28tdHJhY2tlci0zMjcxNyIsImF1dGhfdGltZSI6MTczOTU2NzYwMiwidXNlcl9pZCI6IkJQaHhlTk9GWVVNNzNNUjl3bEJvRVNUQUtYdTEiLCJzdWIiOiJCUGh4ZU5PRllVTTczTVI5d2xCb0VTVEFLWHUxIiwiaWF0IjoxNzM5NTY3NjAyLCJleHAiOjE3Mzk1NzEyMDIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdHVzZXJAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.IB5XiIxmZiQCOnkoc1QMz7EswftzAGRTRRH6f3D0kJ4Hu1dRUHrORRKJcBc6v6fmAAjSzW-E-K3JvDvTFAyW-d8SkYK6tJ3iksjS-VtXArdwJYACOxz-770NQuZa_layXP7WZgkXlA0M6imqRXZpT55aWkh7pRwgQE6TTOrV5_BArai_6FeRZfpDcjg34r0HVUbj0AoI74of-ASzkgS9ejft5YuOG38hNZtEm0QqoGORowgnQcRKViM5RVXT19ETynvbJDEYaXZvRilv4qXoU7frAEugm4Vz78xwv19Mq1H62KE09nTagURrR0zBGEia9OOWiZc-_oahdWv8ErPCRw

### Get all audit logs
GET http://localhost:3000/auditlogs
Authorization: Bearer {{token}}
