@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMjUwZDIyYTkzODVmYzQ4NDJhYTU2YWJhZjUzZmU5NDcxNmVjNTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRyYWNrZXItMzI3MTciLCJhdWQiOiJlY28tdHJhY2tlci0zMjcxNyIsImF1dGhfdGltZSI6MTczOTQ4NDMyNSwidXNlcl9pZCI6Imd0aVJWZ3ZVZjZiQm1mQXFGZFRzVTRZNVpHUTIiLCJzdWIiOiJndGlSVmd2VWY2YkJtZkFxRmRUc1U0WTVaR1EyIiwiaWF0IjoxNzM5NDg0MzI1LCJleHAiOjE3Mzk0ODc5MjUsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdHVzZXJAZXhhbXBsZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.HPPAB75gS3YL7zLKxBRylTkXCCP5Xfe16yTP-UTkrc_5UoRrw68yWgpw74Wx2LTssT1LgOT24SP0vfOuRRFPrlsMQkGlmhc4NdKUYpiLjE0HyGLVWwDXLeK2viylkXOoSMLyDWJ2dkTiA0usR533PwU_Ola8o1aVnUj-aNKUZ_jdfqgv3I0bHUBOp3m9CFgZ1dweU-ATSsHE5s7MUECLypw0NzEo0Y50XNdprBHRf0oU8_7cZnEdRGfkLXv2qnZ3aMuoScopDuSK5Z1zHpxvcO7WjDXMpG2o9OvGP44azsAHEKOQg-QLXYvKjpUjNR3oBPRYqq0gkENN9XAVPYOT1g

### Create a new electric usage
POST http://localhost:3000/electric-usages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "applianceId": 6,
  "frequency": 10
}

### Get all electric usages
GET http://localhost:3000/electric-usages
Authorization: Bearer {{token}}

### Get electric usage by ID
GET http://localhost:3000/electric-usages/1
Authorization: Bearer {{token}}

### Update electric usage
PUT http://localhost:3000/electric-usages/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "frequency": 10
}

### Delete electric usage
DELETE http://localhost:3000/electric-usages/1
Authorization: Bearer {{token}}

### Get all electric usages by user ID
GET http://localhost:3000/electric-usages/user/gtiRVgvUf6bBmfAqFdTsU4Y5ZGQ2
Authorization: Bearer {{token}}