@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkMjUwZDIyYTkzODVmYzQ4NDJhYTU2YWJhZjUzZmU5NDcxNmVjNTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRyYWNrZXItMzI3MTciLCJhdWQiOiJlY28tdHJhY2tlci0zMjcxNyIsImF1dGhfdGltZSI6MTczODc5NDYxMiwidXNlcl9pZCI6IjhpaDRaYnVCdkpYWjBKS1FQcG5ZQ29HOHdlSTMiLCJzdWIiOiI4aWg0WmJ1QnZKWFowSktRUHBuWUNvRzh3ZUkzIiwiaWF0IjoxNzM4Nzk0NjEyLCJleHAiOjE3Mzg3OTgyMTIsImVtYWlsIjoiZWRhcnRlYWdhQHB1Y2UuZWR1LmVjIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImVkYXJ0ZWFnYUBwdWNlLmVkdS5lYyJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.KjL0qIowNt6bUn5JaF1JEgTpUrjxwQ2-eS8RefJ6z2tCldl3K8NG9fghBPz187cccS7OLZxyYCTWUUgwJXVL0H9fenaTDeWDSiRh2PuCl4jAHAneJF34ifHO11W7PYvIhKht9nCSbHxlMb8el5jaSmuRhLYDzOgtngBbNCTR5XUZnF-1svIu4VdYAoOUwtfs27o8rMfB_MQJ0_ukJPQyZo1Ez_N9PDUqMayCC_j_mjv0sp4fYUzZmg5wEwPFNwO82gaGB2PJ_3qT-y50dlidn0Zi4gXLtW7Yzfa5-zzTL3Xj4tZbtKEWfM0IYhnQfCQHDIZcR9DSAuruUVKT5RPd1g

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "testuser",
  "adminId": 0
}

### Get all users
GET http://localhost:3000/users
Authorization: Bearer {{token}}

### Get a user by ID
GET http://localhost:3000/users/1
Authorization: Bearer {{token}}

### Update a user
PUT http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "updateduser",
  "adminId": 1
}

### Delete a user
DELETE http://localhost:3000/users/1
Authorization: Bearer {{token}}